version: '3'
services:
  client:
    restart: always
    build: ./client/
    ports:
     - '4000:4000'
    links:
     - server
  server:
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: songs
    ports:
      - '27017:27017'
    volumes:
      - ./init-mongo:/docker-entrypoint-initdb.d